"""
========================================================
FIGURE: Application-Weighted Product Rankings  — v4
West Africa Precipitation Products — Decision Support
========================================================
Reads scores from the SCORES sheet of the decision tool
Excel file generated by generate_decision_tool.py.

Default path:  outputs/WA_Precipitation_Decision_Tool.xlsx

Produces four publication-quality figures in figures/:

  fig_v4_01_percentile_bands.png   ← IPCC-style percentile band chart
  fig_v4_02_boxplots.png           ← box-plot comparison
  fig_v4_03_histograms.png         ← score distribution histograms
  fig_v4_04_recommendation_heatmap.png  ← original heatmap (kept for reference)

Usage:
  python fig_application_rankings_v4.py
  python fig_application_rankings_v4.py --xlsx outputs/WA_Precipitation_Decision_Tool.xlsx
========================================================
"""

import argparse
import warnings
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpec

warnings.filterwarnings("ignore")

# ── CLI ───────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument(
    "--xlsx",
    default="outputs/WA_Precipitation_Decision_Tool.xlsx",
    help="Path to the decision tool Excel file",
)
args, _ = parser.parse_known_args()

XLSX_PATH = Path(args.xlsx)
FIGS_DIR  = Path("figures")
FIGS_DIR.mkdir(exist_ok=True)

# ── Constants ─────────────────────────────────────────────────────────────────
ZONES = ["Saharian", "Sahelian", "Soudanian", "Guinean", "Guineo-Congolean"]

APPS_ORDERED = [
    "Fire risk monitoring",
    "Wildlife & habitat",
    "Drought early warning",
    "Flood forecasting",
    "Agricultural planning",
    "Hydrological modelling",
    "Climate trend analysis",
]

APP_SHORT = {
    "Fire risk monitoring":   "Fire risk\nmonitoring",
    "Wildlife & habitat":     "Wildlife &\nhabitat",
    "Drought early warning":  "Drought early\nwarning",
    "Flood forecasting":      "Flood\nforecasting",
    "Agricultural planning":  "Agricultural\nplanning",
    "Hydrological modelling": "Hydrological\nmodelling",
    "Climate trend analysis":  "Climate trend\nanalysis",
}

ZONE_COLORS = {
    "Saharian":         "#C8A96E",
    "Sahelian":         "#E8A838",
    "Soudanian":        "#CC6600",
    "Guinean":          "#78C850",
    "Guineo-Congolean": "#1A6B1A",
}

PROD_COLORS = {
    "CHIRPS":        "#1f77b4",
    "ERA5_LAND":     "#9467bd",
    "GPM_IMERG":     "#d62728",
    "MERRA2":        "#e377c2",
    "PERSIANN_CDR":  "#ff7f0e",
    "TERRACLIMATE":  "#17becf",
}

PROD_LABELS = {
    "CHIRPS":        "CHIRPS",
    "ERA5_LAND":     "ERA5-Land",
    "GPM_IMERG":     "GPM IMERG",
    "MERRA2":        "MERRA-2",
    "PERSIANN_CDR":  "PERSIANN-CDR",
    "TERRACLIMATE":  "TerraClimate",
}

PRODUCTS = list(PROD_COLORS.keys())

# ── Helpers ───────────────────────────────────────────────────────────────────
def style_ax(ax, spine_color="#CCCCCC"):
    """Light, clean axis style."""
    for spine in ax.spines.values():
        spine.set_color(spine_color)
        spine.set_linewidth(0.8)
    ax.tick_params(colors="#444444", labelsize=8.5)
    ax.yaxis.grid(True, linestyle="--", linewidth=0.5, color="#E0E0E0", alpha=0.8)
    ax.set_axisbelow(True)


# ── Load scores ───────────────────────────────────────────────────────────────
def load_scores(xlsx_path: Path) -> pd.DataFrame:
    if not xlsx_path.exists():
        raise FileNotFoundError(
            f"\nCannot find: {xlsx_path}\n"
            "Run generate_decision_tool.py first, or pass --xlsx <path>\n"
            "  → Falling back to SYNTHETIC demo data."
        )
    print(f"Reading scores from: {xlsx_path}")
    df = pd.read_excel(xlsx_path, sheet_name="SCORES", engine="openpyxl")
    df.columns = [c.lower().strip() for c in df.columns]
    df = df[df["zone"].isin(ZONES)].copy()
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    df = df.dropna(subset=["score"])
    df = df[df["app"].isin(APPS_ORDERED)].copy()

    # ── Normalise product names ───────────────────────────────────────────────
    # The Excel may use display names ("GPM IMERG", "ERA5-Land", etc.) while
    # PROD_COLORS / PROD_LABELS use underscore keys ("GPM_IMERG", "ERA5_LAND").
    # Build a best-effort mapping: strip, upper, replace spaces/hyphens with _.
    PROD_NAME_MAP = {
        # explicit overrides for known variants
        "GPM IMERG":     "GPM_IMERG",
        "GPM_IMERG":     "GPM_IMERG",
        "GPMIMERG":      "GPM_IMERG",
        "ERA5-LAND":     "ERA5_LAND",
        "ERA5_LAND":     "ERA5_LAND",
        "ERA5 LAND":     "ERA5_LAND",
        "ERA5LAND":      "ERA5_LAND",
        "PERSIANN-CDR":  "PERSIANN_CDR",
        "PERSIANN_CDR":  "PERSIANN_CDR",
        "PERSIANN CDR":  "PERSIANN_CDR",
        "PERSIANNCDR":   "PERSIANN_CDR",
        "TERRACLIMATE":  "TERRACLIMATE",
        "TERRA CLIMATE": "TERRACLIMATE",
        "TERRA-CLIMATE": "TERRACLIMATE",
        "MERRA-2":       "MERRA2",
        "MERRA2":        "MERRA2",
        "MERRA 2":       "MERRA2",
        "CHIRPS":        "CHIRPS",
    }

    def _normalise_product(name: str) -> str:
        key = str(name).strip().upper().replace("-", "_").replace(" ", "_")
        # Try exact explicit map first
        display = str(name).strip().upper()
        if display in PROD_NAME_MAP:
            return PROD_NAME_MAP[display]
        # Fallback: replace spaces/hyphens with underscores
        return key

    df["product"] = df["product"].apply(_normalise_product)

    print(f"  Loaded {len(df)} rows.")
    print(f"  Product values after normalisation: {sorted(df['product'].unique())}")
    return df


def make_synthetic_scores() -> pd.DataFrame:
    """
    Fallback: reconstruct the scores that were hard-coded in the original
    notebook / image so the figures run without the Excel file.
    """
    print("  *** Using synthetic (hard-coded) scores — no Excel file found ***")

    raw = {
        # (app, zone): {product: score}
        ("Fire risk monitoring",   "Saharian"):         {"GPM_IMERG":0.853,"PERSIANN_CDR":0.828,"CHIRPS":0.801,"ERA5_LAND":0.775,"MERRA2":0.762,"TERRACLIMATE":0.750},
        ("Fire risk monitoring",   "Sahelian"):         {"GPM_IMERG":0.956,"CHIRPS":0.935,"TERRACLIMATE":0.912,"PERSIANN_CDR":0.901,"MERRA2":0.885,"ERA5_LAND":0.870},
        ("Fire risk monitoring",   "Soudanian"):        {"GPM_IMERG":0.919,"CHIRPS":0.914,"PERSIANN_CDR":0.893,"TERRACLIMATE":0.878,"MERRA2":0.862,"ERA5_LAND":0.845},
        ("Fire risk monitoring",   "Guinean"):          {"GPM_IMERG":0.895,"CHIRPS":0.887,"PERSIANN_CDR":0.870,"TERRACLIMATE":0.855,"MERRA2":0.840,"ERA5_LAND":0.825},
        ("Fire risk monitoring",   "Guineo-Congolean"): {"GPM_IMERG":0.945,"CHIRPS":0.909,"PERSIANN_CDR":0.895,"TERRACLIMATE":0.880,"MERRA2":0.865,"ERA5_LAND":0.850},

        ("Wildlife & habitat",     "Saharian"):         {"GPM_IMERG":0.863,"PERSIANN_CDR":0.859,"CHIRPS":0.830,"ERA5_LAND":0.790,"MERRA2":0.775,"TERRACLIMATE":0.760},
        ("Wildlife & habitat",     "Sahelian"):         {"GPM_IMERG":0.967,"TERRACLIMATE":0.949,"CHIRPS":0.930,"PERSIANN_CDR":0.915,"MERRA2":0.900,"ERA5_LAND":0.885},
        ("Wildlife & habitat",     "Soudanian"):        {"GPM_IMERG":0.939,"CHIRPS":0.931,"PERSIANN_CDR":0.915,"TERRACLIMATE":0.900,"MERRA2":0.885,"ERA5_LAND":0.870},
        ("Wildlife & habitat",     "Guinean"):          {"GPM_IMERG":0.908,"CHIRPS":0.891,"PERSIANN_CDR":0.875,"TERRACLIMATE":0.860,"MERRA2":0.845,"ERA5_LAND":0.830},
        ("Wildlife & habitat",     "Guineo-Congolean"): {"GPM_IMERG":0.951,"CHIRPS":0.918,"PERSIANN_CDR":0.903,"TERRACLIMATE":0.888,"MERRA2":0.873,"ERA5_LAND":0.858},

        ("Drought early warning",  "Saharian"):         {"GPM_IMERG":0.865,"PERSIANN_CDR":0.843,"CHIRPS":0.820,"ERA5_LAND":0.785,"MERRA2":0.770,"TERRACLIMATE":0.755},
        ("Drought early warning",  "Sahelian"):         {"GPM_IMERG":0.964,"TERRACLIMATE":0.944,"CHIRPS":0.925,"PERSIANN_CDR":0.910,"MERRA2":0.895,"ERA5_LAND":0.880},
        ("Drought early warning",  "Soudanian"):        {"GPM_IMERG":0.937,"CHIRPS":0.933,"PERSIANN_CDR":0.917,"TERRACLIMATE":0.902,"MERRA2":0.887,"ERA5_LAND":0.872},
        ("Drought early warning",  "Guinean"):          {"GPM_IMERG":0.915,"CHIRPS":0.907,"PERSIANN_CDR":0.891,"TERRACLIMATE":0.876,"MERRA2":0.861,"ERA5_LAND":0.846},
        ("Drought early warning",  "Guineo-Congolean"): {"GPM_IMERG":0.954,"CHIRPS":0.925,"PERSIANN_CDR":0.910,"TERRACLIMATE":0.895,"MERRA2":0.880,"ERA5_LAND":0.865},

        ("Flood forecasting",      "Saharian"):         {"PERSIANN_CDR":0.815,"GPM_IMERG":0.815,"CHIRPS":0.798,"ERA5_LAND":0.720,"MERRA2":0.705,"TERRACLIMATE":0.690},
        ("Flood forecasting",      "Sahelian"):         {"GPM_IMERG":0.958,"TERRACLIMATE":0.939,"CHIRPS":0.920,"PERSIANN_CDR":0.905,"MERRA2":0.890,"ERA5_LAND":0.875},
        ("Flood forecasting",      "Soudanian"):        {"CHIRPS":0.924,"GPM_IMERG":0.924,"PERSIANN_CDR":0.908,"TERRACLIMATE":0.893,"MERRA2":0.878,"ERA5_LAND":0.863},
        ("Flood forecasting",      "Guinean"):          {"GPM_IMERG":0.906,"PERSIANN_CDR":0.882,"CHIRPS":0.870,"TERRACLIMATE":0.855,"MERRA2":0.840,"ERA5_LAND":0.825},
        ("Flood forecasting",      "Guineo-Congolean"): {"GPM_IMERG":0.949,"PERSIANN_CDR":0.914,"CHIRPS":0.902,"TERRACLIMATE":0.887,"MERRA2":0.872,"ERA5_LAND":0.857},

        ("Agricultural planning",  "Saharian"):         {"GPM_IMERG":0.867,"PERSIANN_CDR":0.858,"CHIRPS":0.835,"ERA5_LAND":0.795,"MERRA2":0.780,"TERRACLIMATE":0.765},
        ("Agricultural planning",  "Sahelian"):         {"GPM_IMERG":0.967,"TERRACLIMATE":0.948,"CHIRPS":0.929,"PERSIANN_CDR":0.914,"MERRA2":0.899,"ERA5_LAND":0.884},
        ("Agricultural planning",  "Soudanian"):        {"GPM_IMERG":0.940,"CHIRPS":0.929,"PERSIANN_CDR":0.913,"TERRACLIMATE":0.898,"MERRA2":0.883,"ERA5_LAND":0.868},
        ("Agricultural planning",  "Guinean"):          {"GPM_IMERG":0.906,"CHIRPS":0.888,"PERSIANN_CDR":0.872,"TERRACLIMATE":0.857,"MERRA2":0.842,"ERA5_LAND":0.827},
        ("Agricultural planning",  "Guineo-Congolean"): {"GPM_IMERG":0.949,"CHIRPS":0.916,"PERSIANN_CDR":0.901,"TERRACLIMATE":0.886,"MERRA2":0.871,"ERA5_LAND":0.856},

        ("Hydrological modelling", "Saharian"):         {"PERSIANN_CDR":0.881,"GPM_IMERG":0.872,"CHIRPS":0.850,"ERA5_LAND":0.810,"MERRA2":0.795,"TERRACLIMATE":0.780},
        ("Hydrological modelling", "Sahelian"):         {"GPM_IMERG":0.972,"TERRACLIMATE":0.958,"CHIRPS":0.939,"PERSIANN_CDR":0.924,"MERRA2":0.909,"ERA5_LAND":0.894},
        ("Hydrological modelling", "Soudanian"):        {"GPM_IMERG":0.947,"CHIRPS":0.938,"PERSIANN_CDR":0.922,"TERRACLIMATE":0.907,"MERRA2":0.892,"ERA5_LAND":0.877},
        ("Hydrological modelling", "Guinean"):          {"GPM_IMERG":0.914,"CHIRPS":0.891,"PERSIANN_CDR":0.875,"TERRACLIMATE":0.860,"MERRA2":0.845,"ERA5_LAND":0.830},
        ("Hydrological modelling", "Guineo-Congolean"): {"GPM_IMERG":0.955,"CHIRPS":0.923,"PERSIANN_CDR":0.908,"TERRACLIMATE":0.893,"MERRA2":0.878,"ERA5_LAND":0.863},

        ("Climate trend analysis", "Saharian"):         {"GPM_IMERG":0.875,"PERSIANN_CDR":0.867,"CHIRPS":0.844,"ERA5_LAND":0.805,"MERRA2":0.790,"TERRACLIMATE":0.775},
        ("Climate trend analysis", "Sahelian"):         {"GPM_IMERG":0.968,"TERRACLIMATE":0.950,"CHIRPS":0.931,"PERSIANN_CDR":0.916,"MERRA2":0.901,"ERA5_LAND":0.886},
        ("Climate trend analysis", "Soudanian"):        {"GPM_IMERG":0.942,"CHIRPS":0.930,"PERSIANN_CDR":0.914,"TERRACLIMATE":0.899,"MERRA2":0.884,"ERA5_LAND":0.869},
        ("Climate trend analysis", "Guinean"):          {"GPM_IMERG":0.909,"CHIRPS":0.889,"PERSIANN_CDR":0.873,"TERRACLIMATE":0.858,"MERRA2":0.843,"ERA5_LAND":0.828},
        ("Climate trend analysis", "Guineo-Congolean"): {"GPM_IMERG":0.950,"CHIRPS":0.917,"PERSIANN_CDR":0.902,"TERRACLIMATE":0.887,"MERRA2":0.872,"ERA5_LAND":0.857},
    }

    rows = []
    for (app, zone), prod_scores in raw.items():
        for prod, score in prod_scores.items():
            rows.append({"app": app, "zone": zone, "product": prod, "score": score})
    return pd.DataFrame(rows)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 1  — IPCC-style percentile band chart
# ════════════════════════════════════════════════════════════════════════════════
def fig_percentile_bands(df: pd.DataFrame):
    """
    For each product, compute score percentiles across all
    (app × zone) combinations and plot:
      - shaded band p5–p95  (light)
      - shaded band p25–p75 (darker)
      - median line
      - individual zone dots with ±1 std error bars (mean across apps per zone)
    x-axis = products ordered by median score (mimics the 'time' axis in the example).
    """
    products_ordered = (
        df.groupby("product")["score"]
        .median()
        .sort_values()
        .index.tolist()
    )

    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor("white")
    style_ax(ax)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    x = np.arange(len(products_ordered))

    # ── Percentile bands ──────────────────────────────────────
    p5   = [df.loc[df["product"] == p, "score"].quantile(0.05) for p in products_ordered]
    p25  = [df.loc[df["product"] == p, "score"].quantile(0.25) for p in products_ordered]
    p50  = [df.loc[df["product"] == p, "score"].quantile(0.50) for p in products_ordered]
    p75  = [df.loc[df["product"] == p, "score"].quantile(0.75) for p in products_ordered]
    p95  = [df.loc[df["product"] == p, "score"].quantile(0.95) for p in products_ordered]

    # Overall band colour (use GPM IMERG green-ish teal for neutral)
    band_color = "#2E8B7A"

    ax.fill_between(x, p5,  p95, color=band_color, alpha=0.15, label="p5–p95 range")
    ax.fill_between(x, p25, p75, color=band_color, alpha=0.30, label="p25–p75 range")
    ax.plot(x, p50, color=band_color, linewidth=2.2,
            label="Median across all zones & apps", zorder=4)

    # ── Per-zone dots + error bars ────────────────────────────
    for zone, zcolor in ZONE_COLORS.items():
        y_means, y_stds = [], []
        for prod in products_ordered:
            sub = df.loc[(df["product"] == prod) & (df["zone"] == zone), "score"]
            y_means.append(sub.mean())
            y_stds.append(sub.std() if len(sub) > 1 else 0)
        ax.errorbar(
            x, y_means, yerr=y_stds,
            fmt="o", color=zcolor, markersize=7,
            capsize=3, linewidth=0, elinewidth=1.4,
            ecolor=zcolor, alpha=0.85,
            label=zone, zorder=5,
        )

    # ── Percentile labels at right edge ──────────────────────
    x_label = len(products_ordered) - 0.55
    for val, label in zip([p95[-1], p75[-1], p50[-1], p25[-1], p5[-1]],
                          ["p95", "p75", "median", "p25", "p5"]):
        ax.text(x_label, val, label, va="center", fontsize=8,
                color=band_color, fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(
        [PROD_LABELS.get(p, p) for p in products_ordered],
        fontsize=9.5, fontweight="bold"
    )
    ax.set_ylabel("Application-weighted score", fontsize=10, color="#333")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:.2f}"))
    ax.set_xlim(-0.6, len(products_ordered) - 0.35)
    ax.set_title(
        "Score distribution by product — percentile bands + per-zone means\n"
        "Products ordered by median score  |  Dots = mean across applications per zone  |  "
        "Error bars = ±1 SD",
        fontsize=11, fontweight="bold", color="#1C2D40", pad=12,
    )

    # Legend — two rows
    handles, labels = ax.get_legend_handles_labels()
    ax.legend(
        handles, labels,
        loc="upper left", fontsize=8.5, framealpha=0.9,
        edgecolor="#CCCCCC", ncol=2,
    )

    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_01_percentile_bands.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 2  — Box plots
# ════════════════════════════════════════════════════════════════════════════════
def fig_boxplots(df: pd.DataFrame):
    """
    Two panels:
      Left  — box plots per product (distribution across all zones & apps)
      Right — box plots per zone    (distribution across all products & apps)
    """
    products_ordered = (
        df.groupby("product")["score"]
        .median()
        .sort_values(ascending=False)
        .index.tolist()
    )

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.patch.set_facecolor("white")

    # ── Left: by product ──────────────────────────────────────
    ax = axes[0]
    style_ax(ax)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    data_prod = [df.loc[df["product"] == p, "score"].values for p in products_ordered]
    bp = ax.boxplot(
        data_prod,
        vert=True, patch_artist=True,
        medianprops=dict(color="white", linewidth=2),
        whiskerprops=dict(linewidth=1.2),
        capprops=dict(linewidth=1.2),
        flierprops=dict(marker="o", markersize=4, alpha=0.5),
        widths=0.55,
    )
    for patch, prod in zip(bp["boxes"], products_ordered):
        patch.set_facecolor(PROD_COLORS.get(prod, "#888"))
        patch.set_alpha(0.82)
        patch.set_linewidth(0)

    # Overlay individual zone means as dots
    for xi, prod in enumerate(products_ordered, start=1):
        for zone, zcolor in ZONE_COLORS.items():
            val = df.loc[(df["product"] == prod) & (df["zone"] == zone), "score"].mean()
            if not np.isnan(val):
                ax.scatter(xi, val, color=zcolor, s=28, zorder=5,
                           edgecolors="white", linewidths=0.6)

    ax.set_xticks(range(1, len(products_ordered) + 1))
    ax.set_xticklabels(
        [PROD_LABELS.get(p, p) for p in products_ordered],
        rotation=25, ha="right", fontsize=9,
    )
    ax.set_ylabel("Application-weighted score", fontsize=10)
    ax.set_title("Score distribution by product\n(dots = per-zone means)",
                 fontsize=10.5, fontweight="bold", color="#1C2D40")

    # ── Right: by zone ─────────────────────────────────────────
    ax = axes[1]
    style_ax(ax)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    data_zone = [df[df.zone == z]["score"].values for z in ZONES]
    bp2 = ax.boxplot(
        data_zone,
        vert=True, patch_artist=True,
        medianprops=dict(color="white", linewidth=2),
        whiskerprops=dict(linewidth=1.2),
        capprops=dict(linewidth=1.2),
        flierprops=dict(marker="o", markersize=4, alpha=0.5),
        widths=0.55,
    )
    for patch, zone in zip(bp2["boxes"], ZONES):
        patch.set_facecolor(ZONE_COLORS.get(zone, "#888"))
        patch.set_alpha(0.82)
        patch.set_linewidth(0)

    # Overlay per-product means as coloured dots
    for xi, zone in enumerate(ZONES, start=1):
        for prod, pcolor in PROD_COLORS.items():
            val = df.loc[(df["zone"] == zone) & (df["product"] == prod), "score"].mean()
            if not np.isnan(val):
                ax.scatter(xi, val, color=pcolor, s=28, zorder=5,
                           edgecolors="white", linewidths=0.6)

    ax.set_xticks(range(1, len(ZONES) + 1))
    ax.set_xticklabels(ZONES, rotation=25, ha="right", fontsize=9)
    ax.set_ylabel("Application-weighted score", fontsize=10)
    ax.set_title("Score distribution by ecological zone\n(dots = per-product means)",
                 fontsize=10.5, fontweight="bold", color="#1C2D40")

    # Zone colour legend
    zone_patches = [mpatches.Patch(facecolor=ZONE_COLORS[z], label=z, alpha=0.82)
                    for z in ZONES]
    axes[1].legend(handles=zone_patches, title="Zone", fontsize=8,
                   loc="lower right", framealpha=0.9, edgecolor="#CCC")

    # Product colour legend
    prod_patches = [mpatches.Patch(facecolor=PROD_COLORS[p],
                                   label=PROD_LABELS.get(p, p), alpha=0.82)
                    for p in PRODUCTS]
    axes[0].legend(handles=prod_patches, title="Product", fontsize=8,
                   loc="lower right", framealpha=0.9, edgecolor="#CCC")

    fig.suptitle(
        "Box-plot comparison of application-weighted scores  |  West Africa 2001–2020",
        fontsize=12, fontweight="bold", color="#1C2D40", y=1.01,
    )
    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_02_boxplots.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 3  — Histograms / KDE
# ════════════════════════════════════════════════════════════════════════════════
def fig_histograms(df: pd.DataFrame):
    """
    Small-multiples: one panel per product, histogram + KDE of scores
    across all zones and applications, coloured by ecological zone.
    """
    try:
        from scipy.stats import gaussian_kde
        HAS_SCIPY = True
    except ImportError:
        HAS_SCIPY = False

    products_ordered = (
        df.groupby("product")["score"]
        .median()
        .sort_values(ascending=False)
        .index.tolist()
    )

    n = len(products_ordered)
    ncols = 3
    nrows = int(np.ceil(n / ncols))

    fig, axes = plt.subplots(nrows, ncols, figsize=(14, 4.5 * nrows),
                             sharex=False, sharey=False)
    axes = axes.flatten()
    fig.patch.set_facecolor("white")

    x_all_min = df["score"].min() - 0.01
    x_all_max = df["score"].max() + 0.01

    for idx, prod in enumerate(products_ordered):
        ax = axes[idx]
        style_ax(ax)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        prod_df = df.loc[df["product"] == prod].copy()
        color   = PROD_COLORS.get(prod, "#888")

        # Overall histogram
        ax.hist(prod_df["score"], bins=12, color=color, alpha=0.35,
                edgecolor="white", linewidth=0.6, density=True)

        # Per-zone KDE or histogram overlay
        for zone, zcolor in ZONE_COLORS.items():
            zone_scores = prod_df.loc[prod_df["zone"] == zone, "score"].values
            if len(zone_scores) < 2:
                continue
            if HAS_SCIPY:
                kde = gaussian_kde(zone_scores, bw_method=0.5)
                xs  = np.linspace(zone_scores.min() - 0.005,
                                  zone_scores.max() + 0.005, 200)
                ax.plot(xs, kde(xs), color=zcolor, linewidth=1.6,
                        alpha=0.85, label=zone)
            else:
                ax.hist(zone_scores, bins=6, color=zcolor, alpha=0.4,
                        edgecolor="white", density=True, label=zone)

        # Mean line
        mean_val = prod_df["score"].mean()
        ax.axvline(mean_val, color=color, linewidth=1.8, linestyle="--",
                   label=f"Mean = {mean_val:.3f}")

        ax.set_title(PROD_LABELS.get(prod, prod),
                     fontsize=11, fontweight="bold", color=color)
        ax.set_xlabel("Score", fontsize=9)
        ax.set_ylabel("Density", fontsize=9)
        ax.set_xlim(x_all_min, x_all_max)
        ax.legend(fontsize=7.5, framealpha=0.85, edgecolor="#CCC",
                  loc="upper left")

    # Hide any unused panels
    for idx in range(n, len(axes)):
        axes[idx].set_visible(False)

    fig.suptitle(
        "Score distributions per product — histogram + per-zone density\n"
        "Dashed line = product mean across all zones & applications  |  "
        "West Africa 2001–2020",
        fontsize=12, fontweight="bold", color="#1C2D40", y=1.01,
    )
    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_03_histograms.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 4  — Heatmap (carried over from v3, unchanged)
# ════════════════════════════════════════════════════════════════════════════════
def fig_heatmap(df: pd.DataFrame):
    zones   = ZONES
    apps    = APPS_ORDERED
    n_zones = len(zones)
    n_apps  = len(apps)
    cell_w, cell_h = 1.0, 0.82

    fig, ax = plt.subplots(figsize=(14, 8))
    fig.patch.set_facecolor("white")
    ax.set_facecolor("none")

    for ai, app in enumerate(apps):
        for zi, zone in enumerate(zones):
            sub = df[(df["app"] == app) & (df["zone"] == zone)].sort_values(
                "score", ascending=False
            )
            if sub.empty:
                continue
            best   = sub.iloc[0]
            second = sub.iloc[1] if len(sub) > 1 else None
            prod, score = best["product"], best["score"]
            color = PROD_COLORS.get(prod, "#888")
            x = zi * cell_w
            y = (n_apps - 1 - ai) * cell_h

            rect = mpatches.FancyBboxPatch(
                (x + 0.035, y + 0.035), cell_w - 0.07, cell_h - 0.07,
                boxstyle="round,pad=0.025", linewidth=0,
                facecolor=color, alpha=0.87, zorder=2,
            )
            ax.add_patch(rect)
            ax.text(x + cell_w / 2, y + cell_h * 0.64, PROD_LABELS.get(prod, prod),
                    ha="center", va="center", fontsize=9.2, fontweight="bold",
                    color="white", zorder=3)
            ax.text(x + cell_w / 2, y + cell_h * 0.38, f"score = {score:.3f}",
                    ha="center", va="center", fontsize=7.8, color="white",
                    alpha=0.93, zorder=3)
            if second is not None:
                ax.text(x + cell_w / 2, y + cell_h * 0.13,
                        f"2nd: {PROD_LABELS.get(second['product'], second['product'])}"
                        f" ({second['score']:.3f})",
                        ha="center", va="center", fontsize=6.2, color="white",
                        alpha=0.78, zorder=3, style="italic")

    for zi, zone in enumerate(zones):
        ax.text(zi * cell_w + cell_w / 2, n_apps * cell_h + 0.14,
                zone, ha="center", va="bottom", fontsize=10.5, fontweight="bold",
                color=ZONE_COLORS.get(zone, "#555"))
    for ai, app in enumerate(apps):
        y = (n_apps - 1 - ai) * cell_h + cell_h / 2
        ax.text(-0.16, y, app, ha="right", va="center",
                fontsize=9.5, color="#1C2D40", fontweight="bold")
    for zi in range(n_zones + 1):
        ax.axvline(zi * cell_w, color="#C8D0DC", linewidth=0.55, zorder=1)
    for ai in range(n_apps + 1):
        ax.axhline(ai * cell_h, color="#C8D0DC", linewidth=0.55, zorder=1)

    handles = [mpatches.Patch(facecolor=PROD_COLORS[p], label=PROD_LABELS.get(p, p),
                               linewidth=0, alpha=0.87) for p in PROD_COLORS]
    ax.legend(handles=handles, title="Product", title_fontsize=9,
              loc="lower center", bbox_to_anchor=(0.5, -0.12),
              ncol=6, fontsize=9, frameon=True, framealpha=0.96, edgecolor="#D0D7E0")
    ax.set_xlim(-0.06, n_zones * cell_w + 0.04)
    ax.set_ylim(-0.04, n_apps * cell_h + 0.5)
    ax.axis("off")
    ax.set_title(
        "Top-ranked precipitation product by management application and ecological zone\n"
        "Application-weighted composite scores  |  Italic = 2nd-best  |  West Africa 2001–2020",
        fontsize=11.5, fontweight="bold", color="#1C2D40", pad=14, loc="left",
    )
    plt.tight_layout(rect=[0.14, 0.09, 1.0, 1.0])
    out = FIGS_DIR / "fig_v4_04_recommendation_heatmap.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 5 — Faceted strip/dot plot: product × zone × application
# Each panel = one product. Rows = applications, dots coloured by zone.
# Shows every score in the dataset simultaneously.
# ════════════════════════════════════════════════════════════════════════════════
def fig_app_strip(df: pd.DataFrame):
    """
    Strip (dot) plot with all three dimensions visible:
      - X axis  : score
      - Y axis  : application (within each panel)
      - Dot colour : ecological zone
      - Panels (columns) : product

    Dots are jittered vertically so overlapping points stay readable.
    A horizontal line marks the per-application mean across zones.
    """
    products_ordered = (
        df.groupby("product")["score"]
        .median()
        .sort_values(ascending=False)
        .index.tolist()
    )
    n_prod = len(products_ordered)
    n_apps = len(APPS_ORDERED)

    fig, axes = plt.subplots(
        1, n_prod, figsize=(4.2 * n_prod, 6.5),
        sharey=True, sharex=False
    )
    fig.patch.set_facecolor("white")

    rng = np.random.default_rng(42)

    for pi, (prod, ax) in enumerate(zip(products_ordered, axes)):
        style_ax(ax)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_visible(pi == 0)

        prod_df = df.loc[df["product"] == prod]
        x_min = prod_df["score"].min() - 0.005
        x_max = prod_df["score"].max() + 0.005

        for ai, app in enumerate(APPS_ORDERED):
            app_df = prod_df.loc[prod_df["app"] == app]

            # Mean line across zones for this app
            mean_score = app_df["score"].mean()
            ax.hlines(ai, x_min, x_max, color="#DDDDDD", linewidth=0.8, zorder=1)
            ax.vlines(mean_score, ai - 0.35, ai + 0.35,
                      color=PROD_COLORS.get(prod, "#888"), linewidth=1.8,
                      zorder=2, alpha=0.7)

            # Individual zone dots with jitter
            for zone, zcolor in ZONE_COLORS.items():
                row = app_df.loc[app_df["zone"] == zone, "score"]
                if row.empty:
                    continue
                score_val = row.values[0]
                jitter = rng.uniform(-0.22, 0.22)
                ax.scatter(score_val, ai + jitter,
                           color=zcolor, s=55, zorder=4,
                           edgecolors="white", linewidths=0.5, alpha=0.92)

        ax.set_xlim(x_min - 0.002, x_max + 0.002)
        ax.set_title(PROD_LABELS.get(prod, prod),
                     fontsize=10.5, fontweight="bold",
                     color=PROD_COLORS.get(prod, "#1C2D40"), pad=8)
        ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:.2f}"))
        ax.tick_params(axis="x", labelsize=7.5, rotation=30)
        if pi == 0:
            ax.set_yticks(range(n_apps))
            ax.set_yticklabels(
                [APP_SHORT.get(a, a) for a in APPS_ORDERED],
                fontsize=8, color="#1C2D40"
            )
        ax.set_xlabel("Score", fontsize=8.5)

    # Zone legend
    zone_handles = [
        mpatches.Patch(facecolor=ZONE_COLORS[z], label=z, alpha=0.9)
        for z in ZONES
    ]
    fig.legend(handles=zone_handles, title="Ecological zone",
               title_fontsize=9, loc="lower center",
               bbox_to_anchor=(0.5, -0.04), ncol=5,
               fontsize=8.5, frameon=True, framealpha=0.95, edgecolor="#CCC")

    fig.suptitle(
        "Score strip plot: product × application × ecological zone\n"
        "Vertical bar = application mean across zones  |  "
        "Dots = individual zone scores  |  West Africa 2001–2020",
        fontsize=12, fontweight="bold", color="#1C2D40", y=1.02,
    )
    plt.tight_layout(rect=[0, 0.06, 1, 1])
    out = FIGS_DIR / "fig_v4_05_app_strip.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 6 — Bubble heatmap: application × zone, bubble size = score gap,
#             bubble colour = best product, all products shown as small satellites
# ════════════════════════════════════════════════════════════════════════════════
def fig_app_bubble(df: pd.DataFrame):
    """
    Grid of application (rows) × zone (columns).
    Each cell shows:
      - A large central bubble coloured by the winning product,
        sized by the score of that winner.
      - Six small satellite dots arranged in a ring, one per product,
        sized by their individual score — so you can see all products
        and applications in one view.
    """
    apps  = APPS_ORDERED
    zones = ZONES
    products = list(PROD_COLORS.keys())
    n_apps  = len(apps)
    n_zones = len(zones)

    fig, ax = plt.subplots(figsize=(13, 8))
    fig.patch.set_facecolor("white")
    ax.set_facecolor("#F9FAFB")
    for spine in ax.spines.values():
        spine.set_color("#E0E0E0")

    # Satellite positions (angles around centre)
    sat_angles = np.linspace(0, 2 * np.pi, len(products), endpoint=False)
    sat_r = 0.30   # radius of satellite ring (in data units)

    score_min = df["score"].min()
    score_max = df["score"].max()

    def score_to_size(s, s_min=score_min, s_max=score_max,
                      min_pt=60, max_pt=900):
        return min_pt + (s - s_min) / (s_max - s_min + 1e-9) * (max_pt - min_pt)

    for ai, app in enumerate(apps):
        for zi, zone in enumerate(zones):
            cx, cy = zi, n_apps - 1 - ai   # cell centre

            cell = df.loc[(df["app"] == app) & (df["zone"] == zone)]
            if cell.empty:
                continue
            cell_sorted = cell.sort_values("score", ascending=False)

            # ── Large central bubble = winner ──────────────────
            best  = cell_sorted.iloc[0]
            bprod = best["product"]
            bscore= best["score"]
            ax.scatter(cx, cy,
                       s=score_to_size(bscore) * 1.6,
                       color=PROD_COLORS.get(bprod, "#888"),
                       alpha=0.25, zorder=2)
            ax.scatter(cx, cy,
                       s=score_to_size(bscore) * 0.55,
                       color=PROD_COLORS.get(bprod, "#888"),
                       alpha=0.85, zorder=3,
                       edgecolors="white", linewidths=0.8)

            # ── Satellite dots = all products ──────────────────
            for pi, prod in enumerate(products):
                row = cell.loc[cell["product"] == prod, "score"]
                if row.empty:
                    continue
                s_val = row.values[0]
                sx = cx + sat_r * np.cos(sat_angles[pi])
                sy = cy + sat_r * np.sin(sat_angles[pi])
                ax.scatter(sx, sy,
                           s=score_to_size(s_val, min_pt=8, max_pt=80),
                           color=PROD_COLORS.get(prod, "#888"),
                           alpha=0.82, zorder=4,
                           edgecolors="white", linewidths=0.4)

    # Grid lines
    for zi in range(n_zones):
        ax.axvline(zi - 0.5, color="#E0E0E0", linewidth=0.6)
    for ai in range(n_apps):
        ax.axhline(ai - 0.5, color="#E0E0E0", linewidth=0.6)

    # Axis labels
    ax.set_xticks(range(n_zones))
    ax.set_xticklabels(zones, fontsize=9.5, fontweight="bold")
    for tick, zone in zip(ax.get_xticklabels(), zones):
        tick.set_color(ZONE_COLORS.get(zone, "#333"))
    ax.set_yticks(range(n_apps))
    ax.set_yticklabels(
        [APP_SHORT.get(a, a).replace("\n", " ") for a in reversed(apps)],
        fontsize=9, color="#1C2D40", fontweight="bold"
    )
    ax.set_xlim(-0.6, n_zones - 0.4)
    ax.set_ylim(-0.6, n_apps - 0.4)
    ax.tick_params(length=0)

    # Legend: products
    prod_handles = [
        mpatches.Patch(facecolor=PROD_COLORS[p],
                       label=PROD_LABELS.get(p, p), alpha=0.85)
        for p in products
    ]
    ax.legend(handles=prod_handles, title="Product (large bubble = winner)",
              title_fontsize=8.5, fontsize=8,
              loc="upper left", bbox_to_anchor=(1.01, 1.0),
              framealpha=0.95, edgecolor="#CCC")

    ax.set_title(
        "Bubble heatmap: application × zone  —  all products shown\n"
        "Large central bubble = best product  |  "
        "Small satellites = all other products (size ∝ score)  |  "
        "West Africa 2001–2020",
        fontsize=11, fontweight="bold", color="#1C2D40", pad=12,
    )
    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_06_app_bubble.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 7 — Grouped bar: application × product, panels = zones
# Shows how each product ranks within every application, for each zone.
# ════════════════════════════════════════════════════════════════════════════════
def fig_app_zone_bars(df: pd.DataFrame):
    """
    Small-multiples (one panel per zone).
    Within each panel:
      X axis  = application
      Grouped bars = products
      Bar height = score
    Lets you compare all three dimensions in one figure.
    """
    products = list(PROD_COLORS.keys())
    n_prod   = len(products)
    n_apps   = len(APPS_ORDERED)
    bar_w    = 0.11
    x_base   = np.arange(n_apps)

    score_min = df["score"].min()
    score_max = df["score"].max()
    y_lo = max(0.0, score_min - 0.03)
    y_hi = min(1.02, score_max + 0.02)

    fig, axes = plt.subplots(1, len(ZONES), figsize=(22, 5.5), sharey=True)
    fig.patch.set_facecolor("white")

    for zi, (zone, ax) in enumerate(zip(ZONES, axes)):
        style_ax(ax)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.set_facecolor("#FAFAFA")

        for pi, prod in enumerate(products):
            offsets = x_base + (pi - n_prod / 2 + 0.5) * bar_w
            vals = []
            for app in APPS_ORDERED:
                row = df.loc[
                    (df["product"] == prod) &
                    (df["zone"]    == zone) &
                    (df["app"]     == app), "score"
                ]
                vals.append(row.values[0] if not row.empty else np.nan)

            bars = ax.bar(
                offsets, vals,
                width=bar_w * 0.88,
                color=PROD_COLORS.get(prod, "#888"),
                alpha=0.85, linewidth=0, zorder=3
            )

            # Mark the winning bar with a star
            for xi, (bar, val) in enumerate(zip(bars, vals)):
                if np.isnan(val):
                    continue
                best_score = df.loc[
                    (df["zone"] == zone) & (df["app"] == APPS_ORDERED[xi]),
                    "score"
                ].max()
                if abs(val - best_score) < 1e-6:
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        val + 0.002, "★",
                        ha="center", va="bottom", fontsize=6,
                        color=PROD_COLORS.get(prod, "#888"),
                    )

        ax.set_ylim(y_lo, y_hi)
        ax.set_xticks(x_base)
        ax.set_xticklabels(
            [APP_SHORT.get(a, a) for a in APPS_ORDERED],
            fontsize=6.8, rotation=35, ha="right", color="#333"
        )
        ax.set_title(zone, fontsize=10, fontweight="bold",
                     color=ZONE_COLORS.get(zone, "#333"), pad=6)
        if zi == 0:
            ax.set_ylabel("Score", fontsize=9)
        ax.yaxis.set_major_formatter(
            mticker.FuncFormatter(lambda v, _: f"{v:.2f}")
        )

    # Shared product legend
    prod_handles = [
        mpatches.Patch(facecolor=PROD_COLORS[p],
                       label=PROD_LABELS.get(p, p), alpha=0.85)
        for p in products
    ]
    fig.legend(handles=prod_handles, title="Product  (★ = best in cell)",
               title_fontsize=9, fontsize=8.5,
               loc="lower center", bbox_to_anchor=(0.5, -0.18),
               ncol=6, frameon=True, framealpha=0.95, edgecolor="#CCC")

    fig.suptitle(
        "Score by application, product, and ecological zone\n"
        "Each panel = one zone  |  Grouped bars = products  |  ★ = best product per application  |  "
        "West Africa 2001–2020",
        fontsize=12, fontweight="bold", color="#1C2D40", y=1.04,
    )
    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_07_app_zone_bars.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 8 — Box plots styled like fig_v4_02 but with APPLICATION as axis
# Left panel : application on x-axis, boxes coloured by product
# Right panel: application on x-axis, boxes coloured by zone
# ════════════════════════════════════════════════════════════════════════════════
def fig_app_boxplots(df: pd.DataFrame):
    """
    Same two-panel layout as fig_v4_02 (boxplots) but applications drive the
    x-axis so you can see how difficulty / score varies across use cases.

    Left  — one box per (application × product), coloured by product.
             Overlay dots = per-zone means.
    Right — one box per (application × zone), coloured by zone.
             Overlay dots = per-product means.
    """
    products = list(PROD_COLORS.keys())
    n_prod   = len(products)
    n_apps   = len(APPS_ORDERED)
    n_zones  = len(ZONES)

    fig, axes = plt.subplots(1, 2, figsize=(20, 7))
    fig.patch.set_facecolor("white")

    score_min = df["score"].min()
    score_max = df["score"].max()
    y_lo = max(0.0, score_min - 0.04)
    y_hi = min(1.02, score_max + 0.03)

    # ── Left panel: grouped by application, coloured by product ──────────────
    ax = axes[0]
    style_ax(ax)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    box_w   = 0.10
    gap     = 0.18          # gap between application groups
    x_ticks = []
    x_labels= []

    for ai, app in enumerate(APPS_ORDERED):
        group_centre = ai * (n_prod * box_w + gap)
        x_ticks.append(group_centre + (n_prod - 1) * box_w / 2)
        x_labels.append(APP_SHORT.get(app, app))

        for pi, prod in enumerate(products):
            xpos = group_centre + pi * box_w
            data = df.loc[
                (df["app"] == app) & (df["product"] == prod), "score"
            ].values
            if len(data) == 0:
                continue

            bp = ax.boxplot(
                data, positions=[xpos], widths=box_w * 0.82,
                patch_artist=True, manage_ticks=False,
                medianprops=dict(color="white", linewidth=1.8),
                whiskerprops=dict(linewidth=1.0, color="#666"),
                capprops=dict(linewidth=1.0, color="#666"),
                flierprops=dict(marker="o", markersize=3,
                                markerfacecolor="#aaa", alpha=0.5),
            )
            bp["boxes"][0].set_facecolor(PROD_COLORS.get(prod, "#888"))
            bp["boxes"][0].set_alpha(0.82)
            bp["boxes"][0].set_linewidth(0)

            # Overlay per-zone means as small coloured dots
            for zone, zcolor in ZONE_COLORS.items():
                val = df.loc[
                    (df["app"] == app) &
                    (df["product"] == prod) &
                    (df["zone"] == zone), "score"
                ]
                if not val.empty:
                    ax.scatter(xpos, val.values[0], color=zcolor,
                               s=22, zorder=5, edgecolors="white",
                               linewidths=0.4)

    ax.set_xticks(x_ticks)
    ax.set_xticklabels(
        [l.replace("\n", " ") for l in x_labels],
        fontsize=8, rotation=28, ha="right", color="#1C2D40"
    )
    ax.set_ylim(y_lo, y_hi)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:.2f}"))
    ax.set_ylabel("Application-weighted score", fontsize=10)
    ax.set_title("Score distribution by application\n(boxes = products, dots = zones)",
                 fontsize=10.5, fontweight="bold", color="#1C2D40")

    prod_handles = [
        mpatches.Patch(facecolor=PROD_COLORS[p],
                       label=PROD_LABELS.get(p, p), alpha=0.82)
        for p in products
    ]
    ax.legend(handles=prod_handles, title="Product", fontsize=8,
              loc="lower right", framealpha=0.9, edgecolor="#CCC")

    # ── Right panel: grouped by application, coloured by zone ────────────────
    ax = axes[1]
    style_ax(ax)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    x_ticks2 = []
    x_labels2 = []

    for ai, app in enumerate(APPS_ORDERED):
        group_centre = ai * (n_zones * box_w + gap)
        x_ticks2.append(group_centre + (n_zones - 1) * box_w / 2)
        x_labels2.append(APP_SHORT.get(app, app))

        for zi, zone in enumerate(ZONES):
            xpos = group_centre + zi * box_w
            data = df.loc[
                (df["app"] == app) & (df["zone"] == zone), "score"
            ].values
            if len(data) == 0:
                continue

            bp = ax.boxplot(
                data, positions=[xpos], widths=box_w * 0.82,
                patch_artist=True, manage_ticks=False,
                medianprops=dict(color="white", linewidth=1.8),
                whiskerprops=dict(linewidth=1.0, color="#666"),
                capprops=dict(linewidth=1.0, color="#666"),
                flierprops=dict(marker="o", markersize=3,
                                markerfacecolor="#aaa", alpha=0.5),
            )
            bp["boxes"][0].set_facecolor(ZONE_COLORS.get(zone, "#888"))
            bp["boxes"][0].set_alpha(0.82)
            bp["boxes"][0].set_linewidth(0)

            # Overlay per-product means
            for prod, pcolor in PROD_COLORS.items():
                val = df.loc[
                    (df["app"] == app) &
                    (df["zone"] == zone) &
                    (df["product"] == prod), "score"
                ]
                if not val.empty:
                    ax.scatter(xpos, val.values[0], color=pcolor,
                               s=22, zorder=5, edgecolors="white",
                               linewidths=0.4)

    ax.set_xticks(x_ticks2)
    ax.set_xticklabels(
        [l.replace("\n", " ") for l in x_labels2],
        fontsize=8, rotation=28, ha="right", color="#1C2D40"
    )
    ax.set_ylim(y_lo, y_hi)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:.2f}"))
    ax.set_ylabel("Application-weighted score", fontsize=10)
    ax.set_title("Score distribution by application\n(boxes = zones, dots = products)",
                 fontsize=10.5, fontweight="bold", color="#1C2D40")

    zone_handles = [
        mpatches.Patch(facecolor=ZONE_COLORS[z], label=z, alpha=0.82)
        for z in ZONES
    ]
    ax.legend(handles=zone_handles, title="Zone", fontsize=8,
              loc="lower right", framealpha=0.9, edgecolor="#CCC")

    fig.suptitle(
        "Box-plot comparison of application-weighted scores by application area\n"
        "West Africa 2001–2020",
        fontsize=13, fontweight="bold", color="#1C2D40", y=1.01,
    )
    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_08_app_boxplots.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════════════════════════
# FIGURE 9 — Histograms / KDE styled like fig_v4_03 but panels = applications
# Each panel = one application area.
# Overall histogram + per-product KDE lines (coloured by product).
# Second set of panels with per-zone KDE lines.
# ════════════════════════════════════════════════════════════════════════════════
def fig_app_histograms(df: pd.DataFrame):
    """
    Two rows of small-multiples, one panel per application:

    Top row    — histogram of all scores for that application +
                 per-PRODUCT KDE curves (coloured by product).
                 Dashed line = application mean across all products & zones.

    Bottom row — same histogram + per-ZONE KDE curves (coloured by zone).
    """
    try:
        from scipy.stats import gaussian_kde
        HAS_SCIPY = True
    except ImportError:
        HAS_SCIPY = False

    n_apps = len(APPS_ORDERED)
    ncols  = n_apps
    x_global_min = df["score"].min() - 0.01
    x_global_max = df["score"].max() + 0.01

    fig, axes = plt.subplots(2, ncols, figsize=(4.5 * ncols, 9),
                             sharex=True, sharey=False)
    fig.patch.set_facecolor("white")

    for ai, app in enumerate(APPS_ORDERED):
        app_df   = df.loc[df["app"] == app]
        mean_val = app_df["score"].mean()
        short    = APP_SHORT.get(app, app).replace("\n", "\n")

        # ── Top row: KDE by product ───────────────────────────
        ax_top = axes[0, ai]
        style_ax(ax_top)
        ax_top.spines["top"].set_visible(False)
        ax_top.spines["right"].set_visible(False)

        ax_top.hist(app_df["score"], bins=10, color="#CCCCCC",
                    alpha=0.45, edgecolor="white", linewidth=0.5,
                    density=True, zorder=1)

        for prod, pcolor in PROD_COLORS.items():
            pscores = app_df.loc[app_df["product"] == prod, "score"].values
            if len(pscores) < 2:
                continue
            if HAS_SCIPY:
                kde = gaussian_kde(pscores, bw_method=0.45)
                xs  = np.linspace(x_global_min, x_global_max, 300)
                ax_top.plot(xs, kde(xs), color=pcolor, linewidth=1.8,
                            alpha=0.88, label=PROD_LABELS.get(prod, prod),
                            zorder=3)
            else:
                ax_top.hist(pscores, bins=6, color=pcolor, alpha=0.4,
                            edgecolor="white", density=True,
                            label=PROD_LABELS.get(prod, prod))

        ax_top.axvline(mean_val, color="#333333", linewidth=1.6,
                       linestyle="--",
                       label=f"Mean = {mean_val:.3f}", zorder=4)

        ax_top.set_xlim(x_global_min, x_global_max)
        ax_top.set_title(short, fontsize=9.5, fontweight="bold",
                         color="#1C2D40", pad=6)
        if ai == 0:
            ax_top.set_ylabel("Density\n(by product)", fontsize=9)
        ax_top.legend(fontsize=6.5, framealpha=0.85, edgecolor="#CCC",
                      loc="upper left", ncol=1)

        # ── Bottom row: KDE by zone ───────────────────────────
        ax_bot = axes[1, ai]
        style_ax(ax_bot)
        ax_bot.spines["top"].set_visible(False)
        ax_bot.spines["right"].set_visible(False)

        ax_bot.hist(app_df["score"], bins=10, color="#CCCCCC",
                    alpha=0.45, edgecolor="white", linewidth=0.5,
                    density=True, zorder=1)

        for zone, zcolor in ZONE_COLORS.items():
            zscores = app_df.loc[app_df["zone"] == zone, "score"].values
            if len(zscores) < 2:
                continue
            if HAS_SCIPY:
                kde = gaussian_kde(zscores, bw_method=0.45)
                xs  = np.linspace(x_global_min, x_global_max, 300)
                ax_bot.plot(xs, kde(xs), color=zcolor, linewidth=1.8,
                            alpha=0.88, label=zone, zorder=3)
            else:
                ax_bot.hist(zscores, bins=6, color=zcolor, alpha=0.4,
                            edgecolor="white", density=True, label=zone)

        ax_bot.axvline(mean_val, color="#333333", linewidth=1.6,
                       linestyle="--",
                       label=f"Mean = {mean_val:.3f}", zorder=4)

        ax_bot.set_xlim(x_global_min, x_global_max)
        ax_bot.set_xlabel("Score", fontsize=8.5)
        if ai == 0:
            ax_bot.set_ylabel("Density\n(by zone)", fontsize=9)
        ax_bot.legend(fontsize=6.5, framealpha=0.85, edgecolor="#CCC",
                      loc="upper left", ncol=1)

    fig.suptitle(
        "Score distributions per application area\n"
        "Top row: per-product KDE  |  Bottom row: per-zone KDE  |  "
        "Dashed = application mean  |  West Africa 2001–2020",
        fontsize=12, fontweight="bold", color="#1C2D40", y=1.02,
    )
    plt.tight_layout()
    out = FIGS_DIR / "fig_v4_09_app_histograms.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    try:
        scores_df = load_scores(XLSX_PATH)
    except FileNotFoundError as e:
        print(e)
        scores_df = make_synthetic_scores()

    print("\nGenerating figures...")
    fig_percentile_bands(scores_df)
    fig_boxplots(scores_df)
    fig_histograms(scores_df)
    fig_heatmap(scores_df)

    print("\nGenerating new application-dimension figures...")
    fig_app_strip(scores_df)
    fig_app_bubble(scores_df)
    fig_app_zone_bars(scores_df)
    fig_app_boxplots(scores_df)
    fig_app_histograms(scores_df)

    print("\nAll done. Figures saved to:", FIGS_DIR.resolve())
    print("\nFigure index:")
    print("  fig_v4_01_percentile_bands.png   — IPCC-style band chart (products × zones)")
    print("  fig_v4_02_boxplots.png           — Box plots by product and by zone")
    print("  fig_v4_03_histograms.png         — Score histograms per product")
    print("  fig_v4_04_recommendation_heatmap.png — Classic recommendation grid")
    print("  fig_v4_05_app_strip.png          — Strip plot: product × application × zone")
    print("  fig_v4_06_app_bubble.png         — Bubble heatmap: application × zone")
    print("  fig_v4_07_app_zone_bars.png      — Grouped bars: application × product × zone")
    print("  fig_v4_08_app_boxplots.png       — Box plots by APPLICATION (products & zones overlaid)")
    print("  fig_v4_09_app_histograms.png     — Histograms/KDE by APPLICATION (products & zones)")
    print("  fig_v4_05_app_strip.png          — Strip plot: product × application × zone")
    print("  fig_v4_06_app_bubble.png         — Bubble heatmap: application × zone, all products")
    print("  fig_v4_07_app_zone_bars.png      — Grouped bars: application × product × zone")