"""
========================================================
FIGURE: Application-Weighted Product Rankings
West Africa Precipitation Products — Decision Support
========================================================
Reads scores from the SCORES sheet of the decision tool
Excel file generated by generate_decision_tool.py.

Default path matches the tool output:
    outputs/WA_Precipitation_Decision_Tool.xlsx

Produces three publication-quality figures in figures/:

  fig_app01_recommendation_heatmap.png
  fig_app02_zone_bar_panels.png
  fig_app03_product_radar.png

Usage:
  python fig_application_rankings_v3.py
  python fig_application_rankings_v3.py --xlsx outputs/WA_Precipitation_Decision_Tool.xlsx
========================================================
"""

import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
from pathlib import Path
import warnings
warnings.filterwarnings("ignore")

# ── CLI ───────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument(
    "--xlsx",
    default="outputs/WA_Precipitation_Decision_Tool.xlsx",
    help="Path to the decision tool Excel file (default: outputs/WA_Precipitation_Decision_Tool.xlsx)"
)
args, _ = parser.parse_known_args()

XLSX_PATH = Path(args.xlsx)
FIGS_DIR  = Path("figures")
FIGS_DIR.mkdir(exist_ok=True)

# ── Constants ─────────────────────────────────────────────────
ZONES = ["Saharian", "Sahelian", "Soudanian", "Guinean", "Guineo-Congolean"]

# Ordered list matches APP_WEIGHTS in generate_decision_tool.py
APPS_ORDERED = [
    "Fire risk monitoring",
    "Wildlife & habitat",
    "Drought early warning",
    "Flood forecasting",
    "Agricultural planning",
    "Hydrological modelling",
    "Climate trend analysis",
]

# Short display labels for tight axes
APP_SHORT = {
    "Fire risk monitoring":   "Fire risk\nmonitoring",
    "Wildlife & habitat":     "Wildlife &\nhabitat",
    "Drought early warning":  "Drought early\nwarning",
    "Flood forecasting":      "Flood\nforecasting",
    "Agricultural planning":  "Agricultural\nplanning",
    "Hydrological modelling": "Hydrological\nmodelling",
    "Climate trend analysis":  "Climate trend\nanalysis",
}

ZONE_COLORS = {
    "Saharian":         "#C8A96E",
    "Sahelian":         "#E8A838",
    "Soudanian":        "#CC6600",
    "Guinean":          "#78C850",
    "Guineo-Congolean": "#1A6B1A",
}

PROD_COLORS = {
    "CHIRPS":        "#1f77b4",
    "ERA5_LAND":     "#9467bd",
    "GPM_IMERG":     "#d62728",
    "MERRA2":        "#e377c2",
    "PERSIANN_CDR":  "#ff7f0e",
    "TERRACLIMATE":  "#17becf",
}

PROD_LABELS = {
    "CHIRPS":        "CHIRPS",
    "ERA5_LAND":     "ERA5-Land",
    "GPM_IMERG":     "GPM IMERG",
    "MERRA2":        "MERRA-2",
    "PERSIANN_CDR":  "PERSIANN-CDR",
    "TERRACLIMATE":  "TerraClimate",
}

# ── Load scores from SCORES sheet ────────────────────────────
def load_scores(xlsx_path: Path) -> pd.DataFrame:
    """
    Read the SCORES sheet which has columns:
        app | zone | product | score | score_key
    This is the flat pre-computed table written by
    build_scores_table() in generate_decision_tool.py.
    Filter to the 5 ecological zones only (exclude All West Africa).
    """
    if not xlsx_path.exists():
        raise FileNotFoundError(
            f"\nCannot find: {xlsx_path}\n"
            f"Run generate_decision_tool.py first, or pass --xlsx <path>"
        )

    print(f"Reading scores from: {xlsx_path}")
    df = pd.read_excel(xlsx_path, sheet_name="SCORES", engine="openpyxl")
    print(f"  SCORES sheet: {df.shape[0]} rows, columns: {list(df.columns)}")

    # Normalise column names (lowercase, strip whitespace)
    df.columns = [c.lower().strip() for c in df.columns]

    # Keep only 5 ecological zones — exclude All West Africa
    df = df[df["zone"].isin(ZONES)].copy()
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    df = df.dropna(subset=["score"])

    # Keep only apps in our ordered list
    df = df[df["app"].isin(APPS_ORDERED)].copy()

    print(f"  After filter: {len(df)} rows")
    print(f"  Apps:     {sorted(df['app'].unique())}")
    print(f"  Zones:    {sorted(df['zone'].unique())}")
    print(f"  Products: {sorted(df['product'].unique())}")
    return df


# ════════════════════════════════════════════════════════════
# FIGURE 1 — Recommendation heatmap
# ════════════════════════════════════════════════════════════
def fig_heatmap(scores_df: pd.DataFrame):
    zones   = ZONES
    apps    = APPS_ORDERED
    n_zones = len(zones)
    n_apps  = len(apps)
    cell_w  = 1.0
    cell_h  = 0.82

    fig, ax = plt.subplots(figsize=(14, 8))
    fig.patch.set_facecolor("white")
    ax.set_facecolor("none")

    for ai, app in enumerate(apps):
        for zi, zone in enumerate(zones):
            sub = scores_df[
                (scores_df["app"]  == app) &
                (scores_df["zone"] == zone)
            ].sort_values("score", ascending=False)

            if sub.empty:
                continue

            best   = sub.iloc[0]
            second = sub.iloc[1] if len(sub) > 1 else None
            prod   = best["product"]
            score  = best["score"]
            color  = PROD_COLORS.get(prod, "#888888")

            x = zi * cell_w
            y = (n_apps - 1 - ai) * cell_h

            rect = mpatches.FancyBboxPatch(
                (x + 0.035, y + 0.035),
                cell_w - 0.07, cell_h - 0.07,
                boxstyle="round,pad=0.025",
                linewidth=0, facecolor=color,
                alpha=0.87, zorder=2
            )
            ax.add_patch(rect)

            ax.text(x + cell_w / 2, y + cell_h * 0.64,
                    PROD_LABELS.get(prod, prod),
                    ha="center", va="center",
                    fontsize=9.2, fontweight="bold",
                    color="white", zorder=3)

            ax.text(x + cell_w / 2, y + cell_h * 0.38,
                    f"score = {score:.3f}",
                    ha="center", va="center",
                    fontsize=7.8, color="white",
                    alpha=0.93, zorder=3)

            if second is not None:
                ax.text(x + cell_w / 2, y + cell_h * 0.13,
                        f"2nd: {PROD_LABELS.get(second['product'], second['product'])}"
                        f" ({second['score']:.3f})",
                        ha="center", va="center",
                        fontsize=6.2, color="white",
                        alpha=0.78, zorder=3, style="italic")

    # Zone headers
    for zi, zone in enumerate(zones):
        ax.text(zi * cell_w + cell_w / 2,
                n_apps * cell_h + 0.14,
                zone, ha="center", va="bottom",
                fontsize=10.5, fontweight="bold",
                color=ZONE_COLORS.get(zone, "#555"))

    # App row labels
    for ai, app in enumerate(apps):
        y = (n_apps - 1 - ai) * cell_h + cell_h / 2
        ax.text(-0.16, y,
                app, ha="right", va="center",
                fontsize=9.5, color="#1C2D40",
                fontweight="bold")

    # Grid
    for zi in range(n_zones + 1):
        ax.axvline(zi * cell_w, color="#C8D0DC", linewidth=0.55, zorder=1)
    for ai in range(n_apps + 1):
        ax.axhline(ai * cell_h, color="#C8D0DC", linewidth=0.55, zorder=1)

    handles = [
        mpatches.Patch(facecolor=PROD_COLORS[p],
                       label=PROD_LABELS.get(p, p),
                       linewidth=0, alpha=0.87)
        for p in PROD_COLORS
    ]
    ax.legend(handles=handles, title="Product", title_fontsize=9,
              loc="lower center", bbox_to_anchor=(0.5, -0.12),
              ncol=6, fontsize=9, frameon=True,
              framealpha=0.96, edgecolor="#D0D7E0")

    ax.set_xlim(-0.06, n_zones * cell_w + 0.04)
    ax.set_ylim(-0.04, n_apps * cell_h + 0.5)
    ax.axis("off")
    ax.set_title(
        "Top-ranked precipitation product by management application and ecological zone\n"
        "Application-weighted composite scores at τ = 1.0 mm/day  |  "
        "Italic = 2nd-best product  |  West Africa 2001–2020",
        fontsize=11.5, fontweight="bold", color="#1C2D40", pad=14, loc="left"
    )

    plt.tight_layout(rect=[0.14, 0.09, 1.0, 1.0])
    out = FIGS_DIR / "fig_app01_recommendation_heatmap.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════
# FIGURE 2 — Zone bar panels (y-axis zoomed to actual range)
# ════════════════════════════════════════════════════════════
def fig_zone_bars(scores_df: pd.DataFrame):
    apps     = APPS_ORDERED
    zones    = ZONES
    products = sorted(scores_df["product"].unique())

    score_min = scores_df["score"].min()
    score_max = scores_df["score"].max()
    y_lo = max(0.0, score_min - 0.04)
    y_hi = min(1.02, score_max + 0.03)

    fig = plt.figure(figsize=(18, 14))
    fig.patch.set_facecolor("white")

    gs = GridSpec(3, 3, figure=fig,
                  hspace=0.55, wspace=0.30,
                  left=0.06, right=0.97,
                  top=0.92, bottom=0.10)

    panel_positions = [
        gs[0,0], gs[0,1], gs[0,2],
        gs[1,0], gs[1,1], gs[1,2],
        gs[2,0],
    ]

    bar_w  = 0.13
    x_base = np.arange(len(zones))

    for pi, (app, pos) in enumerate(zip(apps, panel_positions)):
        ax = fig.add_subplot(pos)
        ax.set_facecolor("none")
        for spine in ax.spines.values():
            spine.set_edgecolor("#D0D7E0")
            spine.set_linewidth(0.8)

        for pi2, prod in enumerate(products):
            offsets = x_base + (pi2 - len(products) / 2 + 0.5) * bar_w
            vals = []
            for zone in zones:
                sub = scores_df[
                    (scores_df["app"]     == app)  &
                    (scores_df["zone"]    == zone) &
                    (scores_df["product"] == prod)
                ]
                vals.append(sub["score"].values[0]
                            if not sub.empty else np.nan)

            ax.bar(offsets, vals,
                   width=bar_w * 0.88,
                   color=PROD_COLORS.get(prod, "#888"),
                   alpha=0.86, zorder=3, linewidth=0)

        ax.set_ylim(y_lo, y_hi)
        ax.yaxis.grid(True, color="#E5E7EB", linewidth=0.6, zorder=0)
        ax.set_axisbelow(True)
        ax.set_xticks(x_base)
        ax.set_xticklabels(
            [z.replace("Guineo-Congolean", "G-Congolean") for z in zones],
            fontsize=8, rotation=20, ha="right", color="#1C2D40"
        )
        tick_vals = np.linspace(y_lo, y_hi, 5)
        ax.set_yticks(tick_vals)
        ax.set_yticklabels([f"{v:.2f}" for v in tick_vals],
                           fontsize=7.5, color="#6B7280")
        ax.set_title(app, fontsize=10, fontweight="bold",
                     color="#1C2D40", pad=6)
        if pi % 3 == 0:
            ax.set_ylabel("Composite score", fontsize=8, color="#6B7280")

    # Legend
    legend_ax = fig.add_subplot(gs[2, 1:])
    legend_ax.set_visible(False)
    handles = [
        mpatches.Patch(facecolor=PROD_COLORS[p], alpha=0.86,
                       label=PROD_LABELS.get(p, p), linewidth=0)
        for p in products
    ]
    fig.legend(handles=handles, title="Precipitation product",
               title_fontsize=9.5, loc="lower right",
               bbox_to_anchor=(0.97, 0.04), ncol=3, fontsize=9,
               frameon=True, framealpha=0.96, edgecolor="#D0D7E0",
               handlelength=1.4, handleheight=1.0)

    for zi, zone in enumerate(zones):
        zx = 0.06 + zi * (0.60 / len(zones))
        fig.text(zx, 0.026, "●", fontsize=12,
                 color=ZONE_COLORS.get(zone, "#888"),
                 ha="center", transform=fig.transFigure)
        fig.text(zx, 0.008,
                 zone.replace("Guineo-Congolean", "G-Congolean"),
                 fontsize=7.5, ha="center",
                 color="#1C2D40", transform=fig.transFigure)

    fig.suptitle(
        "Application-weighted composite scores by product, ecological zone, and management application\n"
        f"Y-axis: {y_lo:.2f}–{y_hi:.2f} (zoomed to actual range)  |  "
        "τ = 1.0 mm/day  |  West Africa 2001–2020",
        fontsize=11.5, fontweight="bold", color="#1C2D40", y=0.97
    )

    out = FIGS_DIR / "fig_app02_zone_bar_panels.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ════════════════════════════════════════════════════════════
# FIGURE 3 — Product radar charts
# ════════════════════════════════════════════════════════════
def fig_radar(scores_df: pd.DataFrame):
    products   = sorted(scores_df["product"].unique())
    apps       = APPS_ORDERED
    n_apps     = len(apps)
    angles     = np.linspace(0, 2 * np.pi, n_apps, endpoint=False).tolist()
    angles    += angles[:1]
    app_labels = [APP_SHORT.get(a, a).replace("\n", " ") for a in apps]

    score_floor = max(0.0, scores_df["score"].min() - 0.06)
    score_ceil  = min(1.0, scores_df["score"].max() + 0.02)

    fig, axs = plt.subplots(
        2, 3, figsize=(16, 10.5),
        subplot_kw=dict(polar=True)
    )
    fig.patch.set_facecolor("white")

    for pi, (prod, ax) in enumerate(zip(products, axs.flat)):
        ax.set_facecolor("none")
        ax.set_theta_offset(np.pi / 2)
        ax.set_theta_direction(-1)
        ax.set_ylim(score_floor, score_ceil)

        rticks = np.linspace(score_floor, score_ceil, 4)
        ax.set_yticks(rticks)
        ax.set_yticklabels([f"{v:.2f}" for v in rticks],
                           fontsize=6.2, color="#9CA3AF")
        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(app_labels, fontsize=7.8, color="#374151")
        ax.tick_params(axis="x", pad=9)
        ax.grid(color="#E5E7EB", linewidth=0.8)
        ax.spines["polar"].set_color("#D1D5DB")

        for zone in ZONES:
            sub = scores_df[
                (scores_df["product"] == prod) &
                (scores_df["zone"]    == zone)
            ]
            vals = []
            for app in apps:
                row = sub[sub["app"] == app]
                vals.append(row["score"].values[0]
                            if not row.empty else score_floor)
            vals += vals[:1]

            zcolor = ZONE_COLORS.get(zone, "#888")
            ax.plot(angles, vals, color=zcolor,
                    linewidth=1.8, alpha=0.92, zorder=3)

        ax.set_title(PROD_LABELS.get(prod, prod),
                     fontsize=11.5, fontweight="bold",
                     color=PROD_COLORS.get(prod, "#1C2D40"), pad=15)

    zone_handles = [
        mpatches.Patch(facecolor=ZONE_COLORS[z], alpha=0.87,
                       label=z, linewidth=0)
        for z in ZONES
    ]
    fig.legend(handles=zone_handles, title="Ecological zone",
               title_fontsize=9, loc="lower center",
               bbox_to_anchor=(0.5, -0.02), ncol=5, fontsize=9,
               frameon=True, framealpha=0.96, edgecolor="#D0D7E0")

    fig.suptitle(
        "Application-weighted composite score profiles by product and ecological zone\n"
        f"Each axis = one management application  |  "
        f"Radial scale: {score_floor:.2f}–{score_ceil:.2f}  |  "
        "τ = 1.0 mm/day  |  West Africa 2001–2020",
        fontsize=11.5, fontweight="bold", color="#1C2D40", y=1.01
    )

    plt.tight_layout(rect=[0, 0.07, 1, 1])
    out = FIGS_DIR / "fig_app03_product_radar.png"
    fig.savefig(out, dpi=300, bbox_inches="tight",
                facecolor="white")
    print(f"Saved: {out.name}")
    plt.close(fig)


# ── Main ─────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n" + "=" * 58)
    print("  Application-Weighted Ranking Figures v3")
    print("=" * 58)
    print(f"  Excel source : {XLSX_PATH}")
    print(f"  Figures out  : {FIGS_DIR}/\n")

    scores_df = load_scores(XLSX_PATH)

    fig_heatmap(scores_df)
    fig_zone_bars(scores_df)
    fig_radar(scores_df)

    print("\n  Done. Three figures generated:")
    print("  • fig_app01_recommendation_heatmap.png")
    print("  • fig_app02_zone_bar_panels.png")
    print("  • fig_app03_product_radar.png")